H = { n = "$214.40space\"см\"$", s = "$0.10space\"см\"$", r = "$214.40 plus.minus 0.10space\"см\"$" }

I = { n = "$7.47space\"г\" dot \"м\"^(2)$", s = "$0.16space\"г\" dot \"м\"^(2)$", r = "$7.47 plus.minus 0.16space\"г\" dot \"м\"^(2)$" }

I1 = { n = "$7.42space\"г\" dot \"м\"^(2)$", s = "$0.06space\"г\" dot \"м\"^(2)$", r = "$7.42 plus.minus 0.06space\"г\" dot \"м\"^(2)$" }

I_d_ring = { n = "$6.805space\"г\" dot \"м\"^(2)$", s = "$0.006space\"г\" dot \"м\"^(2)$", r = "$6.805 plus.minus 0.006space\"г\" dot \"м\"^(2)$" }

I_ring = { n = "$4.665space\"г\" dot \"м\"^(2)$", s = "$0.005space\"г\" dot \"м\"^(2)$", r = "$4.665 plus.minus 0.005space\"г\" dot \"м\"^(2)$" }

Ib_hor = { n = "$4.056space\"г\" dot \"м\"^(2)$", s = "$0.004space\"г\" dot \"м\"^(2)$", r = "$4.056 plus.minus 0.004space\"г\" dot \"м\"^(2)$" }

Ib_vert = { n = "$0.1280space\"г\" dot \"м\"^(2)$", s = "$0.0010space\"г\" dot \"м\"^(2)$", r = "$0.1280 plus.minus 0.0010space\"г\" dot \"м\"^(2)$" }

Id = { n = "$2.1400space\"г\" dot \"м\"^(2)$", s = "$0.0031space\"г\" dot \"м\"^(2)$", r = "$2.1400 plus.minus 0.0031space\"г\" dot \"м\"^(2)$" }

Im = [ { n = "$0.00space\"г\" dot \"м\"^(2)$", s = "$0.22space\"г\" dot \"м\"^(2)$", r = "$0.00 plus.minus 0.22space\"г\" dot \"м\"^(2)$" }
, { n = "$4.68space\"г\" dot \"м\"^(2)$", s = "$0.16space\"г\" dot \"м\"^(2)$", r = "$4.68 plus.minus 0.16space\"г\" dot \"м\"^(2)$" }
, { n = "$2.06space\"г\" dot \"м\"^(2)$", s = "$0.16space\"г\" dot \"м\"^(2)$", r = "$2.06 plus.minus 0.16space\"г\" dot \"м\"^(2)$" }
, { n = "$6.72space\"г\" dot \"м\"^(2)$", s = "$0.16space\"г\" dot \"м\"^(2)$", r = "$6.72 plus.minus 0.16space\"г\" dot \"м\"^(2)$" }
, { n = "$3.85space\"г\" dot \"м\"^(2)$", s = "$0.15space\"г\" dot \"м\"^(2)$", r = "$3.85 plus.minus 0.15space\"г\" dot \"м\"^(2)$" }
, { n = "$0.20space\"г\" dot \"м\"^(2)$", s = "$0.16space\"г\" dot \"м\"^(2)$", r = "$0.20 plus.minus 0.16space\"г\" dot \"м\"^(2)$" }
,]
Ipp = { n = "$1.654space\"г\" dot \"м\"^(2)$", s = "$0.004space\"г\" dot \"м\"^(2)$", r = "$1.654 plus.minus 0.004space\"г\" dot \"м\"^(2)$" }

Ith = [ { n = "$4.665space\"г\" dot \"м\"^(2)$", s = "$0.005space\"г\" dot \"м\"^(2)$", r = "$4.665 plus.minus 0.005space\"г\" dot \"м\"^(2)$" }
, { n = "$2.1400space\"г\" dot \"м\"^(2)$", s = "$0.0031space\"г\" dot \"м\"^(2)$", r = "$2.1400 plus.minus 0.0031space\"г\" dot \"м\"^(2)$" }
, { n = "$6.805space\"г\" dot \"м\"^(2)$", s = "$0.006space\"г\" dot \"м\"^(2)$", r = "$6.805 plus.minus 0.006space\"г\" dot \"м\"^(2)$" }
, { n = "$4.056space\"г\" dot \"м\"^(2)$", s = "$0.004space\"г\" dot \"м\"^(2)$", r = "$4.056 plus.minus 0.004space\"г\" dot \"м\"^(2)$" }
, { n = "$0.1280space\"г\" dot \"м\"^(2)$", s = "$0.0010space\"г\" dot \"м\"^(2)$", r = "$0.1280 plus.minus 0.0010space\"г\" dot \"м\"^(2)$" }
,]
R = { n = "$114.60space\"мм\"$", s = "$0.10space\"мм\"$", r = "$114.60 plus.minus 0.10space\"мм\"$" }

Rk = { n = "$12.40space\"см\"$", s = "$0.05space\"см\"$", r = "$12.40 plus.minus 0.05space\"см\"$" }

b = { n = "$1.779space\"г\" dot \"м\"^(2)$", s = "$0.008space\"г\" dot \"м\"^(2)$", r = "$1.779 plus.minus 0.008space\"г\" dot \"м\"^(2)$" }

g = { n = "$9.810space\"м\" dot \"с\"^(-2)$", s = "$0.010space\"м\" dot \"с\"^(-2)$", r = "$9.810 plus.minus 0.010space\"м\" dot \"с\"^(-2)$" }

i = "раздв диск"
k = { n = "$1597space\"г\"$", s = "$8space\"г\"$", r = "$1597 plus.minus 8space\"г\"$" }

kk = { n = "$401.8space\"мм\"^(2) dot \"с\"^(-2)$", s = "$1.4space\"мм\"^(2) dot \"с\"^(-2)$", r = "$401.8 plus.minus 1.4space\"мм\"^(2) dot \"с\"^(-2)$" }

lb = { n = "$21.090space\"см\"$", s = "$0.010space\"см\"$", r = "$21.090 plus.minus 0.010space\"см\"$" }

m_ring = { n = "$776.6space\"г\"$", s = "$0.5space\"г\"$", r = "$776.6 plus.minus 0.5space\"г\"$" }

mb = { n = "$1077.0space\"г\"$", s = "$0.5space\"г\"$", r = "$1077.0 plus.minus 0.5space\"г\"$" }

md = { n = "$589.6space\"г\"$", s = "$0.5space\"г\"$", r = "$589.6 plus.minus 0.5space\"г\"$" }

mm = { n = "$965.7space\"г\"$", s = "$0.5space\"г\"$", r = "$965.7 plus.minus 0.5space\"г\"$" }

mp = { n = "$1536.2space\"г\"$", s = "$0.5space\"г\"$", r = "$1536.2 plus.minus 0.5space\"г\"$" }

r = { n = "$30.20space\"мм\"$", s = "$0.10space\"мм\"$", r = "$30.20 plus.minus 0.10space\"мм\"$" }

r_ring = { n = "$7.955space\"см\"$", s = "$0.005space\"см\"$", r = "$7.955 plus.minus 0.005space\"см\"$" }

r_ring_inner = { n = "$7.540space\"см\"$", s = "$0.005space\"см\"$", r = "$7.540 plus.minus 0.005space\"см\"$" }

rd = { n = "$8.520space\"см\"$", s = "$0.005space\"см\"$", r = "$8.520 plus.minus 0.005space\"см\"$" }

rp = { n = "$4.640space\"см\"$", s = "$0.005space\"см\"$", r = "$4.640 plus.minus 0.005space\"см\"$" }

wb = { n = "$2.670space\"см\"$", s = "$0.010space\"см\"$", r = "$2.670 plus.minus 0.010space\"см\"$" }

z0 = { n = "$214.04space\"см\"$", s = "$0.10space\"см\"$", r = "$214.04 plus.minus 0.10space\"см\"$" }

[df]
"подвес" = [ [ 10.0, 44.702,], [ 12.0, 53.272,], [ 15.0, 66.091,], [ 10.0, 43.978,], [ 10.0, 43.91,], [ 10.0, 43.862,], [ 10.0, 43.828,], [ 10.0, 43.776,], [ 11.0, 48.132,], [ 10.0, 43.698,], [ 10.0, 43.985,], [ 20.0, 85.395,],]
"кольцо" = [ [ 10.0, 41.705,], [ 10.0, 41.681,], [ 10.0, 41.638,], [ 10.0, 41.676,], [ 10.0, 41.593,],]
"диск" = [ [ 10.0, 39.078,], [ 10.0, 39.1,], [ 10.0, 39.044,], [ 10.0, 39.016,], [ 10.0, 39.013,],]
"кольцо+диск" = [ [ 10.0, 38.947,], [ 10.0, 38.932,], [ 10.0, 38.928,], [ 10.0, 38.916,], [ 10.0, 38.913,],]
"брусок горизонт" = [ [ 10.0, 37.154,], [ 10.0, 37.129,], [ 10.0, 37.163,],]
"брусок вертик" = [ [ 10.0, 29.829,], [ 10.0, 29.78,], [ 10.0, 29.714,],]
"раздв диск" = [ [ 10.0, 30.336, 1.0,], [ 10.0, 30.394, 1.0,], [ 10.0, 30.345, 1.0,], [ 10.0, 30.357, 1.0,], [ 10.0, 30.349, 1.0,], [ 10.0, 30.317, 1.0,], [ 10.0, 30.631, 2.0,], [ 10.0, 30.615, 2.0,], [ 10.0, 30.599, 2.0,], [ 10.0, 30.985, 3.0,], [ 10.0, 30.99, 3.0,], [ 10.0, 30.903, 3.0,], [ 10.0, 31.45, 4.0,], [ 10.0, 31.433, 4.0,], [ 10.0, 31.429, 4.0,], [ 10.0, 31.984, 5.0,], [ 10.0, 31.97, 5.0,], [ 10.0, 31.964, 5.0,], [ 10.0, 32.606, 6.0,], [ 10.0, 32.555, 6.0,], [ 10.0, 32.548, 6.0,], [ 10.0, 33.424, 7.0,], [ 10.0, 33.364, 7.0,], [ 10.0, 33.369, 7.0,], [ 10.0, 34.252, 8.0,], [ 10.0, 34.283, 8.0,], [ 10.0, 34.231, 8.0,], [ 10.0, 35.248, 9.0,], [ 10.0, 35.234, 9.0,], [ 10.0, 35.266, 9.0,],]
