D_1 = { n = "$11.070space\"см\"$", s = "$0.010space\"см\"$", r = "$11.070 plus.minus 0.010space\"см\"$" }

G1 = { n = "$76.0space\"ГПа\"$", s = "$1.8space\"ГПа\"$", r = "$76.0 plus.minus 1.8space\"ГПа\"$" }

G2 = { n = "$84.3space\"ГПа\"$", s = "$3.2space\"ГПа\"$", r = "$84.3 plus.minus 3.2space\"ГПа\"$" }

L_1 = { n = "$132.80space\"см\"$", s = "$0.10space\"см\"$", r = "$132.80 plus.minus 0.10space\"см\"$" }

L_2 = { n = "$173.00space\"см\"$", s = "$0.20space\"см\"$", r = "$173.00 plus.minus 0.20space\"см\"$" }

b1 = { n = "$-0.0013space\"radian\"$", s = "$0.0013space\"radian\"$", r = "$-0.0013 plus.minus 0.0013space\"radian\"$" }

b2 = { n = "$2.770space\"с\"^(2)$", s = "$0.007space\"с\"^(2)$", r = "$2.770 plus.minus 0.007space\"с\"^(2)$" }

d_1 = { n = "$4.820space\"мм\"$", s = "$0.010space\"мм\"$", r = "$4.820 plus.minus 0.010space\"мм\"$" }

d_2 = { n = "$1.050space\"мм\"$", s = "$0.010space\"мм\"$", r = "$1.050 plus.minus 0.010space\"мм\"$" }

df1 = [ [ 12.0, 52.26, 52.29, 52.29,], [ 9.0, 44.9, 44.86, 44.89,], [ 6.0, 37.61, 37.65, 37.64,], [ 3.0, 30.74, 30.73, 30.73,], [ 0.0, 24.49, 24.47, 24.49,],]
df2 = [ [ 200.0, 4.4, 5.0, 4.5,], [ 400.0, 8.5, 8.7, 9.1,], [ 500.0, 11.6, 11.4, 12.0,], [ 600.0, 13.5, 14.8, 13.8,], [ 700.0, 16.6, 16.6, 16.9,], [ 800.0, 18.4, 18.5, 18.3,], [ 700.0, 16.7, 16.5, 16.5,], [ 600.0, 14.45, 13.5, 13.9,], [ 500.0, 11.2, 11.3, 11.5,], [ 400.0, 9.2, 8.5, 9.5,], [ 200.0, 4.0, 3.9, 5.0,],]
f1 = { n = "$6.07space\"м\" dot \"Н\"$", s = "$0.14space\"м\" dot \"Н\"$", r = "$6.07 plus.minus 0.14space\"м\" dot \"Н\"$" }

f2 = { n = "$0.011627space\"Н\" dot \"м\"$", s = "$0.000030space\"Н\" dot \"м\"$", r = "$0.011627 plus.minus 0.000030space\"Н\" dot \"м\"$" }

g = { n = "$9.810space\"м\" dot \"с\"^(-2)$", s = "$0.010space\"м\" dot \"с\"^(-2)$", r = "$9.810 plus.minus 0.010space\"м\" dot \"с\"^(-2)$" }

k1 = { n = "$0.165space\"м\"^(-1) dot \"Н\"^(-1)$", s = "$0.004space\"м\"^(-1) dot \"Н\"^(-1)$", r = "$0.165 plus.minus 0.004space\"м\"^(-1) dot \"Н\"^(-1)$" }

k2 = { n = "$0.06944space\"с\"^(2) dot \"см\"^(-2)$", s = "$0.00005space\"с\"^(2) dot \"см\"^(-2)$", r = "$0.06944 plus.minus 0.00005space\"с\"^(2) dot \"см\"^(-2)$" }

l_off_2 = { n = "$4.780space\"см\"$", s = "$0.010space\"см\"$", r = "$4.780 plus.minus 0.010space\"см\"$" }

l_weight_2 = { n = "$4.060space\"см\"$", s = "$0.010space\"см\"$", r = "$4.060 plus.minus 0.010space\"см\"$" }

m_2 = { n = "$204.5space\"г\"$", s = "$0.5space\"г\"$", r = "$204.5 plus.minus 0.5space\"г\"$" }

